// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnHK0bAzvJ71EDKJFc6gFMPQOcFu-ICIE',
    appId: '1:443273042691:web:b07c0d279e8992f4286736',
    messagingSenderId: '443273042691',
    projectId: 'helpbuddy-79264',
    authDomain: 'helpbuddy-79264.firebaseapp.com',
    storageBucket: 'helpbuddy-79264.appspot.com',
    measurementId: 'G-X70857756G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQV8vMrvXEBg5y415NWcsmA_VFHEziej8',
    appId: '1:443273042691:android:08c7b942d06329ef286736',
    messagingSenderId: '443273042691',
    projectId: 'helpbuddy-79264',
    storageBucket: 'helpbuddy-79264.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3nvB00q5zwDWP8rBzqQl1vIHB0QrbGOE',
    appId: '1:443273042691:ios:c52ac03116acd6da286736',
    messagingSenderId: '443273042691',
    projectId: 'helpbuddy-79264',
    storageBucket: 'helpbuddy-79264.appspot.com',
    iosClientId: '443273042691-m25cm8t6qtkgq5lg5dh26jps19a3va2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpbuddy',
  );
}
